version: '3.8'
services:
  docker_ts_template:
    image: node:14-alpine3.12
    user: node
    command: sh -c "npm install && npm run tscw"
    working_dir: /home/app
    ports:
    - "3000:60701"
    volumes:
    - .:/home/app
    #entrypoint: ["npm", "install"]
    #entrypoint: ["npm", "run", "tscw"]



