version: '3.8'
services:
  docker_ts_template:
    #Intentionally choose a verison when you start development
    image: node:lts-alpine
    user: node
    command: sh -c "npm install && npm run tscw"
    working_dir: /home/app
    ports:
    - "5000:60701"
    volumes:
    - .:/home/app
    #entrypoint: ["npm", "install"]
    #entrypoint: ["npm", "run", "tscw"]



